# Generated by Django 4.2.4 on 2023-09-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publishing_company',
            new_name='PublishingCompany',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.category')),
                ('publishing_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.publishingcompany')),
            ],
        ),
    ]
